name: kanante_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ðŸ”¥ Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_app_check: ^0.3.2+10 # Downgraded for compatibility
  google_sign_in: ^6.2.1
  firebase_database: ^11.1.0
  firebase_storage: ^12.2.0

  # ðŸ“· Multimedia
  image_picker: ^1.1.2
  cached_network_image: ^3.4.0
  share_plus: ^10.0.0
  photo_view: ^0.15.0

  # ðŸ“¦ Utilidades
  provider: ^6.1.2
  
  # ðŸ‘‡ Mantenemos la versiÃ³n nueva que exige tu Flutter
  intl: ^0.20.2
  
  shared_preferences: ^2.3.2
  logger: ^2.4.0
  file_picker: ^8.1.2
  
  # ðŸ› ï¸ Correcciones
  url_launcher: ^6.3.0
  flutter_quill: ^9.5.0   # Mantenemos la versiÃ³n compatible con tu cÃ³digo
  flutter_rating_bar: ^4.0.0 # New dependency
  time_range_picker: ^2.0.0 # New dependency
  
  # ðŸ“ Mapas
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoapp.jpg"
  min_sdk_android: 21

# ðŸª„ LA MAGIA: Esto fuerza a todos a usar la versiÃ³n que queremos
dependency_overrides:
  intl: ^0.20.2